{{- range $key, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $service.namespace }}
  labels:
    name: {{ $service.namespace }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: database-namespace
  labels:
    name: database-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik-ingress
  labels:
    name: traefik-ingress
